version: "3.9"

services:
  device-store:
    image: device-store:latest
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "8080:8080"
    depends_on:
      - redis


  redis:
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"
      - "8001:8001"