name: device-store
on:
  push:
    branches:
      - main
    tags:
      - device-store/v*.*.*
    paths:
      - device-store/**
      - .github/workflows/device-store.yml


jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: device-store
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go 1.19
        uses: actions/setup-go@v4
        with:
          go-version: 1.19
      - name: Install dependencies
        run: make init
      - name: Run tests
        run: make test
  
  deploy-image:
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/')
    defaults:
      run:
        working-directory: device-store
    steps:
      - uses: actions/checkout@v3
      - name: Docker login
        run:  echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build image
        run: |
          tag=$(echo ${{ github.ref_name }} | sed 's/\//-/g') 
          export DOCKER_TAG=$tag
          make build-image
      - name: Push image
        run: |
          tag=$(echo ${{ github.ref_name }} | sed 's/\//-/g')
          docker push "${{ secrets.DOCKERHUB_USERNAME }}/home-automation:$tag"
          
