name: device-store
on:
  push:
    branches:
      - main
    paths:
      - device-store/**


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-go@v4
        with:
          go-version: 1.19
      - name: Install dependencies
        run: make init
      - name: Run tests
        run: make test